apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: development

resources:
- ../base

commonLabels:
  app.kubernetes.io/component: frontend
  app.kubernetes.io/environment: dev

images:
- name: frontend
  newName: raphaelmoraes/digital-step-flow-frontend
  newTag: 0.0.1
- name: raphaelmoraes/digital-step-flow-frontend
  newName: raphaelmoraes/digital-step-flow-frontend
  newTag: 24.13.0-r1-dev

patches:
- patch: |-
    - op: replace
      path: /spec/replicas
      value: 1
  target:
    kind: Deployment
    name: digital-step-flow-frontend
