apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: production

resources:
  - ../base

commonLabels:
  app.kubernetes.io/component: frontend
  app.kubernetes.io/environment: prod

images:
  - name: raphaelmoraes/digital-step-flow-frontend
    newName: raphaelmoraes/digital-step-flow-frontend
    newTag: 0.0.1

patches:
  - target:
      kind: Deployment
      name: digital-step-flow-frontend
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 3
