apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: digital-step-flow-frontend
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/raphaelmoraes/pucrs-tcc-digital-step-flow-frontend
    targetRevision: main
    path: k8s
  destination:
    server: https://kubernetes.default.svc
    namespace: digital-step-flow
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
    - PrunePropagationPolicy=foreground
    - PruneLast=true
  revisionHistoryLimit: 10

