apiVersion: v1
kind: ConfigMap
metadata:
  name: digital-step-flow-config
  namespace: development
data:
  NODE_ENV: "production"
  FRONTEND_URL: "http://digital-step-flow-frontend"
  SERVICE_NAME: "digital-step-flow"
  POSTGRES_HOST: "digital-step-flow-database"
  POSTGRES_DB: "digital_step_flow"
