apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: digital-step-flow-frontend-pdb
  namespace: production
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: digital-step-flow-frontend

